package com.aviva.documentroute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Action implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String actionType;

   public Action()
   {
   }

   public java.lang.String getActionType()
   {
      return this.actionType;
   }

   public void setActionType(java.lang.String actionType)
   {
      this.actionType = actionType;
   }

   public Action(java.lang.String actionType)
   {
      this.actionType = actionType;
   }

}