package com.aviva.documentroute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentTypeSatify implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean satisfy;

   public DocumentTypeSatify()
   {
   }

   public java.lang.Boolean getSatisfy()
   {
      return this.satisfy;
   }

   public void setSatisfy(java.lang.Boolean satisfy)
   {
      this.satisfy = satisfy;
   }

   public DocumentTypeSatify(java.lang.Boolean satisfy)
   {
      this.satisfy = satisfy;
   }

}