package com.aviva.documentroute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentRoute implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String docTypeCd;
   private java.lang.String transactionTypeCd;

   private com.aviva.documentroute.DocCheckList docCheckList;

   private com.aviva.documentroute.RouteInfo routeInfo;

   private java.lang.String returnReason;

   public DocumentRoute()
   {
   }

   public java.lang.String getDocTypeCd()
   {
      return this.docTypeCd;
   }

   public void setDocTypeCd(java.lang.String docTypeCd)
   {
      this.docTypeCd = docTypeCd;
   }

   public java.lang.String getTransactionTypeCd()
   {
      return this.transactionTypeCd;
   }

   public void setTransactionTypeCd(java.lang.String transactionTypeCd)
   {
      this.transactionTypeCd = transactionTypeCd;
   }

   public com.aviva.documentroute.DocCheckList getDocCheckList()
   {
      return this.docCheckList;
   }

   public void setDocCheckList(com.aviva.documentroute.DocCheckList docCheckList)
   {
      this.docCheckList = docCheckList;
   }

   public com.aviva.documentroute.RouteInfo getRouteInfo()
   {
      return this.routeInfo;
   }

   public void setRouteInfo(com.aviva.documentroute.RouteInfo routeInfo)
   {
      this.routeInfo = routeInfo;
   }

   public java.lang.String getReturnReason()
   {
      return this.returnReason;
   }

   public void setReturnReason(java.lang.String returnReason)
   {
      this.returnReason = returnReason;
   }

   public DocumentRoute(java.lang.String docTypeCd,
         java.lang.String transactionTypeCd,
         com.aviva.documentroute.DocCheckList docCheckList,
         com.aviva.documentroute.RouteInfo routeInfo,
         java.lang.String returnReason)
   {
      this.docTypeCd = docTypeCd;
      this.transactionTypeCd = transactionTypeCd;
      this.docCheckList = docCheckList;
      this.routeInfo = routeInfo;
      this.returnReason = returnReason;
   }

}