package com.aviva.documentroute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Document implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String docTypeCd;
   private java.lang.String transactionTypeCd;

   private com.aviva.documentroute.DocCheckList docCheckList;

   public Document()
   {
   }

   public java.lang.String getDocTypeCd()
   {
      return this.docTypeCd;
   }

   public void setDocTypeCd(java.lang.String docTypeCd)
   {
      this.docTypeCd = docTypeCd;
   }

   public java.lang.String getTransactionTypeCd()
   {
      return this.transactionTypeCd;
   }

   public void setTransactionTypeCd(java.lang.String transactionTypeCd)
   {
      this.transactionTypeCd = transactionTypeCd;
   }

   public com.aviva.documentroute.DocCheckList getDocCheckList()
   {
      return this.docCheckList;
   }

   public void setDocCheckList(com.aviva.documentroute.DocCheckList docCheckList)
   {
      this.docCheckList = docCheckList;
   }

   public Document(java.lang.String docTypeCd, java.lang.String transactionTypeCd,
         com.aviva.documentroute.DocCheckList docCheckList)
   {
      this.docTypeCd = docTypeCd;
      this.transactionTypeCd = transactionTypeCd;
      this.docCheckList = docCheckList;
   }

}