package com.aviva.documentroute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocTrxGroup implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;

   public DocTrxGroup()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public DocTrxGroup(java.lang.String name)
   {
      this.name = name;
   }

}