package com.aviva.documentroute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RouteInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RouteInfo() {
    }

}