package com.aviva.documentroute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RouteInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<com.aviva.documentroute.Action> actionList;

   public RouteInfo()
   {
   }

   public java.util.List<com.aviva.documentroute.Action> getActionList()
   {
      return this.actionList;
   }

   public void setActionList(
         java.util.List<com.aviva.documentroute.Action> actionList)
   {
      this.actionList = actionList;
   }

   public RouteInfo(java.util.List<com.aviva.documentroute.Action> actionList)
   {
      this.actionList = actionList;
   }

}