package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.CheckList;
import com.aviva.ezflow.model.documentroute.Conditions;
import com.aviva.ezflow.model.documentroute.DocumentRoute;

rule "create decision object"
	dialect "mvel"
	salience 99
	when
	    DocumentRoute(docCheckList != null)
	then
	    System.out.println("create decision object...");
		insert(new Conditions());
end