package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.DocumentRoute;
import com.aviva.ezflow.model.documentroute.CheckList;
import com.aviva.ezflow.model.documentroute.DocCheckList;

rule "extract checklist from documentroute"
dialect "mvel"
salience 100
when
    $docRoute : DocumentRoute(docCheckList != null)
    $checklist : CheckList( value != null) from $docRoute.docCheckList.checkList
then
    System.out.println("checklist is inserted");
    insert ($checklist);
end