package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.CheckList;
import com.aviva.ezflow.model.documentroute.DocumentRoute;
import com.aviva.ezflow.model.documentroute.DocCheckList;
import java.util.ArrayList;

rule "merge checklist to documentroute"
when
    $docRoute : DocumentRoute
    $checkLists : ArrayList( size > 0 )
              from ( CheckList( name != null) )
then
   // DocCheckList docCheckList = new DocCheckList();
   // docCheckList.setDocCheckList($checkLists);
   // $docRoute.setDocCheckList(docCheckList);
end