package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.CheckList;
import com.aviva.ezflow.model.documentroute.DocumentRoute;
import com.aviva.ezflow.model.documentroute.DocCheckList;
import java.util.ArrayList;
import java.util.List;

rule "merge checklist to documentroute"
when
    $docCheckList : DocCheckList
    $item : CheckList()
then
   // DocCheckList docCheckList = new DocCheckList();
   // docCheckList.setDocCheckList($checkLists);
   // $docRoute.setDocCheckList(docCheckList);
end