package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.RouteInfo
import com.aviva.ezflow.model.documentroute.Action
import com.aviva.ezflow.model.documentroute.RouteInfo

rule "merge action to documentroute"
dialect "mvel"
salience -99
when
    $docRoute : DocumentRoute(this != null, routeInfo == null)
    $items : ArrayList( size > 0 ) from collect ( Action( actionType != null) )
then
    System.out.println("merge action to documentroute");

    RouteInfo routeInfo = new RouteInfo();
    routeInfo.actionList = $items;

    $docRoute.routeInfo = routeInfo;
end