package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.CheckList;
import com.aviva.ezflow.model.documentroute.DocumentRoute;
import com.aviva.ezflow.model.documentroute.DocCheckList;
import java.util.ArrayList;
import java.util.List;

rule "merge checklist to documentroute"
dialect "mvel"
salience -99
when
    $docRoute : DocumentRoute(this != null)
    $docCheckList : $docRoute.docCheckList()
    $items : ArrayList( size > 0 ) from collect ( CheckList( name != null) )
then
    $docCheckList.checkList = $items;

end