package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.RouteInfo;
import com.aviva.ezflow.model.documentroute.Action;
import com.aviva.ezflow.model.documentroute.RouteInfo;

rule "merge action to documentroute"
dialect "mvel"
salience -99
when
    $docRoute : DocumentRoute(this != null)
    $items : ArrayList( size > 0 ) from collect ( Action( actionType != null) )
then

    RouteInfo routeInfo = new RouteInfo();
    routeInfo.actionList = $items;
    
    $docRoute.routeInfo = routeInfo;
end