package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.DocTrxGroup;
import com.aviva.ezflow.model.documentroute.CheckList;
import com.aviva.ezflow.model.documentroute.Conditions;
import com.aviva.ezflow.model.documentroute.Action;
import com.aviva.ezflow.model.documentroute.Property;

rule "print doctrxgroup"
dialect "mvel"
when
    $docgrp : DocTrxGroup(name != null)
then
    
    System.out.println("found DocTrxGroup ..." +  $docgrp.name);
end

rule "print checklist"
dialect "mvel"
when
    $item : CheckList(name != null)
then
    
    System.out.println("found CheckList ..." +  $item.name + "," +  $item.value);
end

rule "print conditions"
dialect "mvel"
when
    $item : Conditions()
then
    System.out.println("--------------------------------------------")
    System.out.println("found Conditions ...");
    System.out.println("contractCreated = " + $item.contractCreated);
    System.out.println("policyStatus = " + $item.policyStatus);
    System.out.println("dispatchDate = " + $item.dispatchDate);
    System.out.println("policyAckReceived = " + $item.policyAckReceived);
    System.out.println("policyHolderReceived = " + $item.policyHolderReceived);
    System.out.println("pompliantReceived = " + $item.compliantReceived);
    System.out.println("incidentReceived = " + $item.incidentReceived);
    System.out.println("cCNeedSupport = " + $item.cCNeedSupport);
    System.out.println("nBProcessExist = " + $item.nBProcessExist);
    System.out.println("nSProcessExist = " + $item.pSProcessExist);
    System.out.println("claimProcessExist = " + $item.claimProcessExist);
    System.out.println("policyOnHold = " + $item.policyOnHold);
    System.out.println("--------------------------------------------")
end

rule "print action"
dialect "mvel"
when
    $item : Action(actionType != null)
then
    
    System.out.println("found Action ..." +  $item.actionType);
end

rule "print action property"
dialect "mvel"
when
    $item : Action(actionType != null)
    $prop : Property() from $item.properties
then
    System.out.println("property - " +  $prop.name + "," $prop.value);
end