package com.aviva.documentroute;

import com.aviva.ezflow.model.documentroute.DocTrxGroup;
import com.aviva.ezflow.model.documentroute.CheckList;

rule "print doctrxgroup"
dialect "mvel"
when
    $docgrp : DocTrxGroup(name != null)
then
    
    System.out.println("found DocTrxGroup ..." +  $docgrp.name);
end

rule "print checklist"
dialect "mvel"
when
    $item : CheckList(name != null)
then
    
    System.out.println("found CheckList ..." +  $item.name + "," +  $item.value);
end